// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCatnSK_KwgqxztHwstu3xhL_w2Go8n020',
    appId: '1:218795790824:web:9fd81e649d9ca6de91d45d',
    messagingSenderId: '218795790824',
    projectId: 'bookingapp-d4d76',
    authDomain: 'bookingapp-d4d76.firebaseapp.com',
    storageBucket: 'bookingapp-d4d76.firebasestorage.app',
    measurementId: 'G-3P9FM6ZSNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWW7nSBLbD9TqTPe9_rdspzjxpc5NGSNQ',
    appId: '1:218795790824:android:29720cec9101abcd91d45d',
    messagingSenderId: '218795790824',
    projectId: 'bookingapp-d4d76',
    storageBucket: 'bookingapp-d4d76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdm5glp1g6dv3IM_fiUa8ooMdVPwMDjNU',
    appId: '1:218795790824:ios:f389d535aad7cf6391d45d',
    messagingSenderId: '218795790824',
    projectId: 'bookingapp-d4d76',
    storageBucket: 'bookingapp-d4d76.firebasestorage.app',
    iosBundleId: 'com.example.bookedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdm5glp1g6dv3IM_fiUa8ooMdVPwMDjNU',
    appId: '1:218795790824:ios:f389d535aad7cf6391d45d',
    messagingSenderId: '218795790824',
    projectId: 'bookingapp-d4d76',
    storageBucket: 'bookingapp-d4d76.firebasestorage.app',
    iosBundleId: 'com.example.bookedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCatnSK_KwgqxztHwstu3xhL_w2Go8n020',
    appId: '1:218795790824:web:ba1e0177f013ded591d45d',
    messagingSenderId: '218795790824',
    projectId: 'bookingapp-d4d76',
    authDomain: 'bookingapp-d4d76.firebaseapp.com',
    storageBucket: 'bookingapp-d4d76.firebasestorage.app',
    measurementId: 'G-TWJRTKEZDG',
  );
}
